function Text_ESN_HPT_Bo1_1()
%
disp([' ', 
      ' Dies ist der Ansichts-Modus "ESN = E senkrecht, Sheet normal auf E"',
      '                         und "HPT = H parallel, Sheet parallel zu H" !',
      ' und zwar für eine aus einem Medium 1 einfallende "gewöhnliche" ebene Welle.',
      ' ',
      ' Die einfallende Welle sei linear polarisiert, wobei E "senkrecht" stehe (s.u.).',
      ' ',
      ' Sie wird an einer ersten ( unendlich ausgedehnten, ebenen ) Grenzfläche',
      ' reflektiert und gebrochen. Dahinter befindet sich ein Medium 2 mit',
      ' i.a. anderen Werten der Dielektrizität, der Leitfähigkeit u. ggfs. der',
      ' Permeabilität.',
      ' Die gebrochene Welle ist aber longitudinal elliptisch polarisiert in H.',
      ' Nur E steht weiterhin "senkrecht". Dieser Wellentyp heisst "TE".',
      ' ',
      ' Das Medium 2 bildet eine Schicht endlicher Dicke, an deren Hinterseite',
      ' ein zweiter, analoger Vorgang Reflexion zurück bzw. Brechung in ein Medium 3',
      ' hinein ( mit i.a. wiederum anderen Materialkonstanten ) bedeutet. ',
      ' Ein Beispiel sei "Luft  --> Glasscheibe --> Wasser". ',
      ' ',
      ' Zur vollständigen Beschreibung der Ausbreitung müssen alle Mehrfachreflexionen',
      ' innerhalb der Schicht 2 berücksichtigt werden.',
      ' ',
      ' Letztendlich kann das Schema auf Mehrfach-Schichten erweitert werden, z.B.auf',
      '   "Luft --> Lack --> Kunststoff --> Grundierung --> Lack --> Luft" , ',
      ' wie es oft bei Antennen hinter Verblendungen vorkommt (Radars am PKW).',
      ' ',
      ' Das elektrische Feld E wird hier besonders gut dargestellt, d.h. KORREKT',
      ' gezeichnet ! - "E senkrecht" bedeutet ja, dass E senkrecht auf der ',
      ' "Einfallsebene" steht, d.h. auf der "x-y-Ebene". Also gibt es nur E_z .',
      ' Die E-Sheets stehen "je normal auf der elektrischen Feldstärke" .',
      ' Darum SIEHT man sie wie "Wasserwellen" !',
      ' Die H-Sheets liegen aber "je parallel zur magnetischen Feldstärke"',
      ' Darum SIEHT man sie als "Scherwellen" ! ( gewöhnungsbedürftig )',
      ' Leider kann man HIER NUR E komplett darstellen !',
      '               Für H gilt :',
      '    1) In EINEM HPT-Sheet kann man das GESAMTE H im "Betrag" zeigen;',
      '       Also geht KEINE Information über die Quer-Verteilung verloren',
      '       ( Besser als bei "HPN" )',
      '    2) Da die gebrochene Welle transversale UND longitudinale Anteile',
      '       NUR im H mit UNTERSCHIEDLICHEN Phasen enthält, wird hier auf',
      '       jede Darstellung "einer longitudinalen Phase" verzichtet !',
      '       Die FARBEN im Sheet entsprechen der rein "transversalen Phase" .']);
%
endfunction