# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Eingabe.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Eingabe(object):
    def setupUi(self, Eingabe):
        Eingabe.setObjectName(_fromUtf8("Eingabe"))
        Eingabe.resize(1140, 550)
        self.lineEdit_Category = QtGui.QLineEdit(Eingabe)
        self.lineEdit_Category.setGeometry(QtCore.QRect(170, 60, 113, 20))
        self.lineEdit_Category.setObjectName(_fromUtf8("lineEdit_Category"))
        self.lineEdit_name = QtGui.QLineEdit(Eingabe)
        self.lineEdit_name.setGeometry(QtCore.QRect(170, 120, 113, 20))
        self.lineEdit_name.setObjectName(_fromUtf8("lineEdit_name"))
        self.label = QtGui.QLabel(Eingabe)
        self.label.setGeometry(QtCore.QRect(40, 60, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Eingabe)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_epsilon_r_fmin = QtGui.QLineEdit(Eingabe)
        self.lineEdit_epsilon_r_fmin.setGeometry(QtCore.QRect(170, 230, 113, 20))
        self.lineEdit_epsilon_r_fmin.setObjectName(_fromUtf8("lineEdit_epsilon_r_fmin"))
        self.label_3 = QtGui.QLabel(Eingabe)
        self.label_3.setGeometry(QtCore.QRect(40, 230, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_kappa_fmin = QtGui.QLineEdit(Eingabe)
        self.lineEdit_kappa_fmin.setGeometry(QtCore.QRect(170, 290, 113, 20))
        self.lineEdit_kappa_fmin.setObjectName(_fromUtf8("lineEdit_kappa_fmin"))
        self.lineEdit_my_r_fmin = QtGui.QLineEdit(Eingabe)
        self.lineEdit_my_r_fmin.setGeometry(QtCore.QRect(170, 350, 113, 20))
        self.lineEdit_my_r_fmin.setObjectName(_fromUtf8("lineEdit_my_r_fmin"))
        self.lineEdit_fmin = QtGui.QLineEdit(Eingabe)
        self.lineEdit_fmin.setGeometry(QtCore.QRect(170, 410, 113, 20))
        self.lineEdit_fmin.setObjectName(_fromUtf8("lineEdit_fmin"))
        self.label_4 = QtGui.QLabel(Eingabe)
        self.label_4.setGeometry(QtCore.QRect(40, 290, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Eingabe)
        self.label_5.setGeometry(QtCore.QRect(40, 350, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Eingabe)
        self.label_6.setGeometry(QtCore.QRect(40, 410, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Eingabe)
        self.label_7.setGeometry(QtCore.QRect(40, 470, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_fmax = QtGui.QLineEdit(Eingabe)
        self.lineEdit_fmax.setGeometry(QtCore.QRect(170, 470, 113, 20))
        self.lineEdit_fmax.setObjectName(_fromUtf8("lineEdit_fmax"))
        self.lineEdit_eps_Fkt_Typ = QtGui.QLineEdit(Eingabe)
        self.lineEdit_eps_Fkt_Typ.setGeometry(QtCore.QRect(490, 230, 113, 20))
        self.lineEdit_eps_Fkt_Typ.setObjectName(_fromUtf8("lineEdit_eps_Fkt_Typ"))
        self.lineEdit_eps_a = QtGui.QLineEdit(Eingabe)
        self.lineEdit_eps_a.setGeometry(QtCore.QRect(650, 230, 113, 20))
        self.lineEdit_eps_a.setObjectName(_fromUtf8("lineEdit_eps_a"))
        self.lineEdit_eps_b = QtGui.QLineEdit(Eingabe)
        self.lineEdit_eps_b.setGeometry(QtCore.QRect(810, 230, 113, 20))
        self.lineEdit_eps_b.setObjectName(_fromUtf8("lineEdit_eps_b"))
        self.lineEdit_kappa_Fkt_Typ = QtGui.QLineEdit(Eingabe)
        self.lineEdit_kappa_Fkt_Typ.setGeometry(QtCore.QRect(490, 290, 113, 20))
        self.lineEdit_kappa_Fkt_Typ.setObjectName(_fromUtf8("lineEdit_kappa_Fkt_Typ"))
        self.lineEdit_kappa_a = QtGui.QLineEdit(Eingabe)
        self.lineEdit_kappa_a.setGeometry(QtCore.QRect(650, 290, 113, 20))
        self.lineEdit_kappa_a.setObjectName(_fromUtf8("lineEdit_kappa_a"))
        self.lineEdit_kappa_b = QtGui.QLineEdit(Eingabe)
        self.lineEdit_kappa_b.setGeometry(QtCore.QRect(810, 290, 113, 20))
        self.lineEdit_kappa_b.setObjectName(_fromUtf8("lineEdit_kappa_b"))
        self.lineEdit_my_Fkt_Typ = QtGui.QLineEdit(Eingabe)
        self.lineEdit_my_Fkt_Typ.setGeometry(QtCore.QRect(490, 350, 113, 20))
        self.lineEdit_my_Fkt_Typ.setObjectName(_fromUtf8("lineEdit_my_Fkt_Typ"))
        self.lineEdit_my_a = QtGui.QLineEdit(Eingabe)
        self.lineEdit_my_a.setGeometry(QtCore.QRect(650, 350, 113, 20))
        self.lineEdit_my_a.setObjectName(_fromUtf8("lineEdit_my_a"))
        self.lineEdit_my_b = QtGui.QLineEdit(Eingabe)
        self.lineEdit_my_b.setGeometry(QtCore.QRect(810, 350, 113, 20))
        self.lineEdit_my_b.setObjectName(_fromUtf8("lineEdit_my_b"))
        self.label_8 = QtGui.QLabel(Eingabe)
        self.label_8.setGeometry(QtCore.QRect(490, 200, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(Eingabe)
        self.label_9.setGeometry(QtCore.QRect(650, 200, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(Eingabe)
        self.label_10.setGeometry(QtCore.QRect(810, 200, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_eps_c = QtGui.QLineEdit(Eingabe)
        self.lineEdit_eps_c.setGeometry(QtCore.QRect(970, 230, 113, 20))
        self.lineEdit_eps_c.setObjectName(_fromUtf8("lineEdit_eps_c"))
        self.lineEdit_kappa_c = QtGui.QLineEdit(Eingabe)
        self.lineEdit_kappa_c.setGeometry(QtCore.QRect(970, 290, 113, 20))
        self.lineEdit_kappa_c.setObjectName(_fromUtf8("lineEdit_kappa_c"))
        self.lineEdit_my_c = QtGui.QLineEdit(Eingabe)
        self.lineEdit_my_c.setGeometry(QtCore.QRect(970, 350, 113, 20))
        self.lineEdit_my_c.setObjectName(_fromUtf8("lineEdit_my_c"))
        self.label_11 = QtGui.QLabel(Eingabe)
        self.label_11.setGeometry(QtCore.QRect(970, 200, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.commit_btn = QtGui.QPushButton(Eingabe)
        self.commit_btn.setGeometry(QtCore.QRect(470, 440, 161, 31))
        self.commit_btn.setObjectName(_fromUtf8("commit_btn"))
        self.lineEdit_epsilon_r_fmax = QtGui.QLineEdit(Eingabe)
        self.lineEdit_epsilon_r_fmax.setGeometry(QtCore.QRect(330, 230, 113, 20))
        self.lineEdit_epsilon_r_fmax.setObjectName(_fromUtf8("lineEdit_epsilon_r_fmax"))
        self.lineEdit_kappa_fmax = QtGui.QLineEdit(Eingabe)
        self.lineEdit_kappa_fmax.setGeometry(QtCore.QRect(330, 290, 113, 20))
        self.lineEdit_kappa_fmax.setObjectName(_fromUtf8("lineEdit_kappa_fmax"))
        self.lineEdit_my_r_fmax = QtGui.QLineEdit(Eingabe)
        self.lineEdit_my_r_fmax.setGeometry(QtCore.QRect(330, 350, 113, 20))
        self.lineEdit_my_r_fmax.setObjectName(_fromUtf8("lineEdit_my_r_fmax"))
        self.label_12 = QtGui.QLabel(Eingabe)
        self.label_12.setGeometry(QtCore.QRect(330, 200, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(Eingabe)
        self.label_13.setGeometry(QtCore.QRect(170, 200, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))

        self.retranslateUi(Eingabe)
        QtCore.QMetaObject.connectSlotsByName(Eingabe)
        Eingabe.setTabOrder(self.lineEdit_Category, self.lineEdit_name)
        Eingabe.setTabOrder(self.lineEdit_name, self.lineEdit_epsilon_r_fmin)
        Eingabe.setTabOrder(self.lineEdit_epsilon_r_fmin, self.lineEdit_epsilon_r_fmax)
        Eingabe.setTabOrder(self.lineEdit_epsilon_r_fmax, self.lineEdit_eps_Fkt_Typ)
        Eingabe.setTabOrder(self.lineEdit_eps_Fkt_Typ, self.lineEdit_eps_a)
        Eingabe.setTabOrder(self.lineEdit_eps_a, self.lineEdit_eps_b)
        Eingabe.setTabOrder(self.lineEdit_eps_b, self.lineEdit_eps_c)
        Eingabe.setTabOrder(self.lineEdit_eps_c, self.lineEdit_kappa_fmin)
        Eingabe.setTabOrder(self.lineEdit_kappa_fmin, self.lineEdit_kappa_fmax)
        Eingabe.setTabOrder(self.lineEdit_kappa_fmax, self.lineEdit_kappa_Fkt_Typ)
        Eingabe.setTabOrder(self.lineEdit_kappa_Fkt_Typ, self.lineEdit_kappa_a)
        Eingabe.setTabOrder(self.lineEdit_kappa_a, self.lineEdit_kappa_b)
        Eingabe.setTabOrder(self.lineEdit_kappa_b, self.lineEdit_kappa_c)
        Eingabe.setTabOrder(self.lineEdit_kappa_c, self.lineEdit_my_r_fmin)
        Eingabe.setTabOrder(self.lineEdit_my_r_fmin, self.lineEdit_my_r_fmax)
        Eingabe.setTabOrder(self.lineEdit_my_r_fmax, self.lineEdit_my_Fkt_Typ)
        Eingabe.setTabOrder(self.lineEdit_my_Fkt_Typ, self.lineEdit_my_a)
        Eingabe.setTabOrder(self.lineEdit_my_a, self.lineEdit_my_b)
        Eingabe.setTabOrder(self.lineEdit_my_b, self.lineEdit_my_c)
        Eingabe.setTabOrder(self.lineEdit_my_c, self.lineEdit_fmin)
        Eingabe.setTabOrder(self.lineEdit_fmin, self.lineEdit_fmax)
        Eingabe.setTabOrder(self.lineEdit_fmax, self.commit_btn)

    def retranslateUi(self, Eingabe):
        Eingabe.setWindowTitle(_translate("Eingabe", "Dialog", None))
        self.label.setText(_translate("Eingabe", "Kategorie", None))
        self.label_2.setText(_translate("Eingabe", "Materialname", None))
        self.label_3.setText(_translate("Eingabe", "epsilon r", None))
        self.label_4.setText(_translate("Eingabe", "kappa", None))
        self.label_5.setText(_translate("Eingabe", "my r", None))
        self.label_6.setText(_translate("Eingabe", "fmin", None))
        self.label_7.setText(_translate("Eingabe", "fmax", None))
        self.label_8.setText(_translate("Eingabe", "Funktionstyp", None))
        self.label_9.setText(_translate("Eingabe", "a", None))
        self.label_10.setText(_translate("Eingabe", "b", None))
        self.label_11.setText(_translate("Eingabe", "c", None))
        self.commit_btn.setText(_translate("Eingabe", "Eintragen", None))
        self.label_12.setText(_translate("Eingabe", "fmax", None))
        self.label_13.setText(_translate("Eingabe", "fmin", None))

